<template>
      <table>
          <tr>
            <th scope="col">Comida</th>
            <th scope="col">Leche</th>
            <th scope="col">Proteina</th>
            <th scope="col">Harinas</th>
            <th scope="col">Verduras</th>
            <th scope="col">Frutas</th>
            <th scope="col">Leguminosas</th>
          </tr>
          <tr>
            <th scope="row">Desayuno</th>
            <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="desayuno">
              </td>
          </tr>
          <tr>
           <th scope="row">Media mañana</th> 
              <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="mediaManana">
              </td>
          </tr>
          <tr>
            <th scope="row">Almuerzo</th> 
               <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="almuerzo">
              </td>
          </tr>
          <tr>
            <th scope="row">Algo</th>
               <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="algo">
              </td>
          </tr>
          <tr>
            <th scope="row">Cena</th>
              <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="cena">
              </td>
          </tr>
          <tr>
            <th scope="row">Refrigerio</th>
               <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="refrigerio">
              </td>
          </tr>
        </table>
       <br>
       <button @click="guardarPlan">Enviar</button> 
</template>
     
<script>
  export default {
        data () {
            return {
                  tienePlan: false,
                  desayuno:[],
                  mediaManana:[],
                  almuerzo:[],
                  algo:[],
                  cena:[],
                  refrigerio:[],
                  tipoAlimentos: ['leche','proteina','harinas','verduras','frutas','leguminosas']
            }
        },
        methods:{
          guardarPlan(){
              console.log('planNutricional')
              console.log(this.desayuno)
          }
        }
        
  }
</script>