<template>
      <table>
          <tr>
            <th scope="col">Comida</th>
            <th scope="col">Leche</th>
            <th scope="col">Proteina</th>
            <th scope="col">Harinas</th>
            <th scope="col">Verduras</th>
            <th scope="col">Frutas</th>
            <th scope="col">Leguminosas</th>
          </tr>
          <tr>
            <th scope="row">Desayuno</th>
            <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="plan.desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="plan.desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="plan.desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="plan.desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="plan.desayuno">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="plan.desayuno">
              </td>
          </tr>
          <tr>
           <th scope="row">Media mañana</th> 
              <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="plan.mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="plan.mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="plan.mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="plan.mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="plan.mediaManana">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="plan.mediaManana">
              </td>
          </tr>
          <tr>
            <th scope="row">Almuerzo</th> 
               <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="plan.almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="plan.almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="plan.almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="plan.almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="plan.almuerzo">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="plan.almuerzo">
              </td>
          </tr>
          <tr>
            <th scope="row">Algo</th>
               <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="plan.algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="plan.algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="plan.algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="plan.algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="plan.algo">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="plan.algo">
              </td>
          </tr>
          <tr>
            <th scope="row">Cena</th>
              <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="plan.cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="plan.cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="plan.cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="plan.cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="plan.cena">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="plan.cena">
              </td>
          </tr>
          <tr>
            <th scope="row">Refrigerio</th>
               <td><input 
                   type="checkbox"
                   value="leche"
                   name="leche"
                   v-model="plan.refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="proteina"
                   name="proteina"
                   v-model="plan.refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="harinas"
                   name="harinas"
                   v-model="plan.refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="verduras"
                   name="verduras"
                   v-model="plan.refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="frutas"
                   name="frutas"
                   v-model="plan.refrigerio">
              </td>
              <td><input 
                   type="checkbox"
                   value="leguminosas"
                   name="leguminosas"
                   v-model="plan.refrigerio">
              </td>
          </tr>
        </table>
       <br>
       <button @click="enviarPlan">Enviar</button> 
</template>
     
<script>
  export default {
        data () {
            return {
               plan:{  
                  desayuno:[],
                  mediaManana:[],
                  almuerzo:[],
                  algo:[],
                  cena:[],
                  refrigerio:[]
               },
               tipoAlimentos: ['leche','proteina','harinas','verduras','frutas','leguminosas']
            }
        },
        methods:{
          async enviarPlan(){
           try{
              await this.$store.dispatch('plan/registroPlan', {
               desayuno:this.plan.desayuno,
               mediaManana:this.plan.mediaManana,
               almuerzo:this.plan.almuerzo,
               algo:this.plan.algo,
               cena:this.plan.cena,
               refrigerio:this.plan.refrigerio
              });
           } catch(err){
              this.error = err.message || 'Fallo envio'
           }
           
           this.$router.replace('/home')
        }

        }
        
  }
</script>